version: "3.9"

services:
  app:
    image: mcr.microsoft.com/devcontainers/php:8.3
    volumes:
      - ..:/workspace:cached
    depends_on:
      - db
    command: sleep infinity

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laraveldb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
